// Regenerates src/fontData.ts from public/fonts/Gaegu-*.woff2.
// Run after replacing those font files with a wider character subset.
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const reg = fs
  .readFileSync(path.join(root, "public/fonts/Gaegu-Regular.woff2"))
  .toString("base64");
const bold = fs
  .readFileSync(path.join(root, "public/fonts/Gaegu-Bold.woff2"))
  .toString("base64");

const content = `// Auto-generated by scripts/embed-font.js - base64 of public/fonts/Gaegu-*.woff2
// Embedding avoids a network fetch for @font-face during headless rendering.
export const gaeguRegularBase64 = "${reg}";
export const gaeguBoldBase64 = "${bold}";
`;

fs.writeFileSync(path.join(root, "src/fontData.ts"), content);
console.log("Wrote src/fontData.ts");
